#-------STQD6134 : Business Analytics Project 1 - Group A-------
###
  #author: 
  # Suraya Balqis Binti Ab.Ghafar (P166248)
  # Rozieyati Azizahtul Asyikin Bte Rozaini (P166417)
  # Fang Jia Hui (P162130/P167347)
  # Nur Dalila Hanan Binti Mior Zulharmin (P167239)
  # Muhammad Aqil Naim Bin Othman (P166244)
  # Ahmad Mujahid Bin Mohd Fadli (P166974)

  #video link : https://youtu.be/uYP2GbekUwk
###

#---Import data---
stream_data <- read.csv("stream_data.csv", header=TRUE, stringsAsFactors=TRUE)
head(stream_data)    # shows first 6 rows of the dataset
summary(stream_data) # shows summary of the dataset
str(stream_data)     # shows structure of the dataset

#-----Task 1 - Preprocessing----

##----(1) Check & handle missing value----
na_counts <- colSums(is.na(stream_data))
"NA counts before CancelDate replacement:"
na_counts

###----i. Convert data type of CancelDate from Factor to Date----
stream_data$CancelDate <- as.Date(stream_data$CancelDate)
str(stream_data$CancelDate)

###----ii. Replace NA with future date "2030-12-31"----
# NA or no value in CancelDate shows the customer is still active, hence replace with future date
stream_data$CancelDate[is.na(stream_data$CancelDate)] <- as.Date("2030-12-31")
na_counts <- colSums(is.na(stream_data))
"NA counts after CancelDate replacement:"
na_counts

##----(2) Convert data type----
###----i. Current data structure----
"Structure before JoinDate & SubscriptionType conversion:"
str(stream_data)

###----ii. Convert data type of JoinDate from Factor to Date----
stream_data$JoinDate <- as.Date(stream_data$JoinDate, origin = "1970-01-01")

###----iii. Change data type of SubscriptionType to Ordinal----
stream_data$SubscriptionType <- factor(stream_data$SubscriptionType, order=TRUE, levels = c("Basic", "Standard", "Premium"))
"Structure after JoinDate & SubscriptionType conversion:"
str(stream_data)

##----(3) New Variables----
###----i. Create new variables "IsActive"----
stream_data$IsActive <- stream_data$CancelDate == as.Date("2030-12-31")  #TRUE if CancelDate=NA which have been replaced by FutureDate


###----ii. Create new variables "MonthJoined"----
library(lubridate)
stream_data$MonthJoined <- month(stream_data$JoinDate, label = TRUE, abbr = TRUE)  #return Months in Mmm format in order.

"Final structure of stream_data:"
str(stream_data)

#-----Task 2 - Business Metric Calculations----

##----(1) Total Revenue - Total Revenue generated during the year.----

TotalRevenue <- sum(stream_data$Revenue, na.rm = TRUE)
TotalRevenue

##----(2) Average Revenue per User (ARPU) – Average revenue per customer.----

ARPU <- mean(stream_data$Revenue, na.rm = TRUE)
ARPU

##----(3) Revenue by Subscription Type - Compare revenue generated by Basic, Standard, and Premium Plans.----

RevenueByType <- aggregate(Revenue ~ SubscriptionType,
                           data = stream_data, sum)
RevenueByType

##----(4) Churn Rate - % of customers who cancelled during the year.----

ChurnRate <- (sum(stream_data$IsActive == FALSE) / nrow(stream_data))*100
ChurnRate

##----(5) Regional Revenue - Total revenue by region.----

RegionalRevenue <- aggregate(Revenue ~ Region,
                             data = stream_data, sum)
RegionalRevenue

##----(6) Average Engagement (Streams per Active Month)----
## - Average number of videos watched per month by customers.

stream_data$Engagement <- stream_data$TotalStreams / stream_data$ActiveMonths
AvgEngagement <- mean(stream_data$Engagement, na.rm = TRUE)
AvgEngagement

##----(7) Monthly Join Trend - Number of new customers joining per months.----

MonthlyJoinTrend <- as.data.frame(table(format(stream_data$JoinDate, "%m")))
MonthlyJoinTrend

##----(8) Device Usage Breakdown - Most common devices used to access the platform.----

DeviceUsage <- as.data.frame(table(stream_data$DeviceType))
DeviceUsage

#-----Task 3 - Visualizations----
library(ggplot2) #Load library to plot visualization

##----(1) Revenue by Subscription Type----
# Use bar graph to compare categorical data
# x-axis : Subscription Type, y-axis : Total Revenue
# Answers: Which subscription plan generates the most revenue?

ggplot(RevenueByType, aes(x = factor(SubscriptionType, levels = c("Basic", "Standard", "Premium")), y = Revenue)) +
  geom_bar(stat = "identity", fill = "cadetblue2") +
  geom_text(aes(label = Revenue), vjust = -0.5, size = 3) +
  labs(title = "Revenue by Subscription Type", x = "Subscription Type", y = "Total Revenue") +
  coord_cartesian(ylim = c(0, max(RevenueByType$Revenue) * 1.5))

##----(2) Revenue by Region----
# Use bar graph to compare total revenue across regions, it highlights regional performance differences.
# Answer: Which region generates the most revenue?

ggplot(RegionalRevenue, aes(x = Region, y = Revenue)) +
  geom_bar(stat = "identity", fill = "wheat1") +
  geom_text(aes(label = Revenue), vjust = -0.5, size = 3) +
  labs(title = "Revenue by Region", x = "Region", y = "Total Revenue") +
  coord_cartesian(ylim = c(0, max(RegionalRevenue$Revenue) * 1.3))

##----(3) Monthly Join Trend----
# Use line chart to show trends over time (months)

# Add new column for month labels and sort it by months instead of alphabetical orders
MonthlyJoinTrend$Month <- factor(MonthlyJoinTrend$Var1, levels = sprintf("%02d", 1:12), labels = month.abb)
# Plot x-axis: Month, y-axis: Number of new customers
ggplot(MonthlyJoinTrend, aes(x = Month, y = Freq, group = 1)) +
  geom_line(color = "navajowhite4") +
  geom_point() +
  labs(title = "Monthly Join Trend", x = "Month", y = "Number of New Customers") +
  theme_minimal()

##----(4) Device Usage----
# Use Pie Chart to show proportions of categorical data
names(DeviceUsage) <- c("Device", "Count")
DeviceUsage$Percentage <- round((DeviceUsage$Count / sum(DeviceUsage$Count)) * 100, 1)

ggplot(DeviceUsage, aes(x = "", y = Count, fill = Device)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y", start = 0) +
  geom_text(aes(label = paste0(Percentage, "%")), position = position_stack(vjust = 0.5), color = "white", fontface = "bold") +
  labs(title = "Device Usage Breakdown", fill = "Device Type") +
  theme_void()

##----(5) Total Streams distribution (to show engagement)----
# Answer Question : How do engagement levels vary across plans or devices?
# Use Histogram to show the distribution of TotalStreams

ggplot(stream_data, aes(x = TotalStreams)) +
  geom_histogram(binwidth = 20, fill = "plum1", color = "black") +
  labs(title = "Distribution of Total Streams (Histogram)", x = "Total Streams", y = "Frequency")

# Justification: We need to compare TotalStreams (continuous) across SubscriptionType (3 categories) and DeviceType (4 categories).
ggplot(stream_data, aes(x = DeviceType, y = TotalStreams, fill = DeviceType)) +
  geom_boxplot() +
  facet_wrap(~ SubscriptionType) +  # Facet by plan for clear separation
  labs(title = "Total Streams by Subscription Type and Device Type",
       x = "Device Type",
       y = "Total Streams",
       fill = "Device Type") +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 45, hjust = 1))  # Rotate x-labels for readability

##----(6) Total Streams by Subscription Type----
ggplot(stream_data, aes(x = SubscriptionType, y = TotalStreams, fill = SubscriptionType)) +
  geom_boxplot() +
  labs(title = "Total Streams by Subscription Type",
       x = "Subscription Plan",
       y = "Total Streams") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5))

##----(7) Total Streams by Devices Type----
ggplot(stream_data, aes(x = DeviceType, y = TotalStreams, fill = DeviceType)) +
  geom_boxplot() +
  labs(title = "Total Streams by Device Type",
       x = "Device Type",
       y = "Total Streams") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 45, hjust = 1))



#-----Task 4 - Insights & Recommendations----
##----(1) Which subscription plan and region generate the most revenue?----
  #From the bar graph of “Revenue by Subscription Type” as shown in part 3, we can see that Premium plan generates the most revenue followed by Standard and Basic from the height of each bar. 
  #Premium plan generates specifically $106230 compare to Standard and Basic which only generate $87320 and $49360 respectively based on table (3.) in part 2. 
  #Comparing across region, North region generates the most revenue followed by East, West and South as per the “Revenue by Region” bar graph. 
  #From the table (5.) in part 2, North region generates $64010. East, West and South region meanwhile is not far off from North region with each of them contributes $62320, $59880 and $56700 respectively towards Streamify’s revenue.

##----(2) What is the overall churn rate and what does it suggest?----
  #The churn rate or the percentage of customers who cancelled Streamify’s plan during last year is 25.05% which compute around a quarter of the total customers.
  #The number is a bit concerning and this needs to be addressed in order to reduce the rate in the future while attracting potential new customers.

##----(3) How do engagement levels (streams) vary across plans or devices?----
  #The engagement levels (streams) can be observed from the box plot "Total Streams by Subscription Plan and Device Type" as shown in part 3.
  #For the Basic plan, the third quartile and maximum value for laptop is the highest compare to three other devices suggest that users stream more videos on laptop.
  #It may be due to the convenience that they might have by watching videos in a proper viewing set up (larger screen compare to mobile and tablet) and still able to watch it anywhere unlike the smart TV.

  #However, for Standard plan’s subscribers, the plot gives an insight that videos streamed on mobile and tablet are higher compare to laptop and smart TV as shown by the median, third quartile and the maximum values.
  #The reason for this might be because Standard plan has more accessible videos compare to the Basic plan.
  #Users have access to a large library of videos, and devices such as mobile phones and tablets offer greater mobility; letting them watch anywhere, anytime, unlike Smart TVs or laptops.

  #The trend changes for the Premium plan with stream volumes for smart TV increases as compared to the previous two plans. The third quartile of the smart TV is the highest followed by the tablet, mobile and the lowest is laptop.
  #Premium plan is the highest tier plan which means; largest video library, no restriction (no ad in the videos), greater video quality with more features.
  #Hence, smart TV provides the best option for binge watching, longer watching durations as well as the best viewing mode (bigger screen) in a home setting.
  #That might be the reasons why the number of videos streamed is high for smart TV.

##----(4) Suggest 1–2 strategies to improve retention or increase revenue?----
  #One of the ways that the company can improve retention is by improvising the user interface.
  #This includes a clean interface, easy navigation and provide personalized recommendations based on the users’ watching history data.
  
  #Another way is by introducing a loyalty program; in which the users can enjoy a discounted monthly subscription fee for all plans if they stayed after a certain period of time (6 months or 1 year).

  #Besides, the number of new customers shows a reduction in Q3, indicating a slowdown in sales growth.
  #This highlights potential weaknesses in the current marketing strategy.
  #Hence, the strategy should be strengthened to attract new customers, drive revenue growth, and ensure a healthy sales pipeline.

#----END----